version: 2.1
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - checkout
      - run:
          name: Node version
          command: |
            echo 'Docker is here'
            docker --version
            node -v