version: 2.1
jobs:
  build:
    docker:
      - image: node:11.10.1

    steps:
      - checkout
      - run:
          name: First step
          command: echo 'CircleCI pipeline'
      - run:
          name: Install React.js Dependencies
          command: |
            npm install
            echo 'Files in current directory are: \n'
            ls
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Build the application to deploy
          command: |
            npm run build
            ls