version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:bionic-20220315

    steps:
      - checkout
      - run:
          name: Node version
          command: |
            echo 'NodeJS is here'
            node -v
            docker -v
      - run:
          command: |
            npm install
            ls
  
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          command: echo 'Deployment succed, congrats!'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build