version: 2.1
jobs:
  build:
    docker:
      - image: node:11.10.1

    steps:
      - checkout
      - run:
          name: Node version
          command: |
            echo 'Docker is here'
            sudo docker --version
            node -v
  
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          command: echo 'deployment'