version: 2.1
jobs:
  build:
    docker:
      - image: node:11.10.1

    steps:
      - checkout
      - run:
          name: First step
          command: echo 'CircleCI pipeline'
      - run:
          name: Second step
          command: |
            ls
            echo 'Thats it for now'