version: 2.1
jobs:
  build:
    docker:
      - image: node:11.10.1

    steps:
      - checkout
      - run:
          name: Node version
          command: |
            echo 'NodeJS is here'
            node -v
      - run:
          command: |
            npm install
            ls
      - run: 
          name: Run Tests
          command: npm run test
  
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          command: |
            echo 'Deployment succed, congrats!'
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build