version: 2.1
jobs:
  build:
    docker:
      - image: node:11.10.1

    steps:
      - checkout
      - run:
          name: Node version
          command: |
            echo 'NodeJS is Installed'
            node -v
      - run:
          name: Installl npm dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm run test
  
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          command: |
            echo 'Starting the deployment job ...'
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP "bash ./deploy.sh "

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build